### ISSUE TITLE
Protocol identifier for stealth addresses

### ISSUE THREAD

**Issue by markblundeberg** [Lokad/Terab#22]
I'm gonna just go ahead and suggest the following OP_RETURN prefix for stealth address payments ( https://www.youtube.com/watch?v=43K_z0sWtEU )

0x0057ea178

looks sort of like "STealTH" to my leet-speek conditioned eyes. :D

**Comment by vermorel** [comment]
Away from office. Returning in 10 days.

**Comment by vermorel** [comment]
Hi Mark,

To claim a protocol identifier, please issue a pull request to add an entry to [protocols.csv](https://github.com/Lokad/Terab/blob/master/etc/protocols.csv). There is a [small webform](http://media.lokad.com/bitcoin/opreturn-prefix-utility.html) to facilitate the process.

Thanks!

**Comment by vermorel** [comment]
Hi @markblundeberg ! The list of protocol prefixes has been moved to https://github.com/bitcoincashorg/bitcoincash.org/blob/master/etc/protocols.csv along with many other community assets. I suggest to repost your request over there if it's still relevant.
