### ISSUE TITLE
Little endian or big endian?

### ISSUE THREAD

**Issue by pmitchev** [Lokad/Terab#34]
Some protocols are using little endian in the list, others are using big endian. Example:
(SLP) https://trends.cash/#/result/cHJlZml4OiA1MzRjNTAwMA==/90
(Bookchain) https://trends.cash/#/result/cHJlZml4OjAwMDBCMDA2/90  
What is the correct way?
Also, the list should use only little OR big endian, not both.

**Comment by vermorel** [comment]
The [guideline specification](https://github.com/Lokad/Terab/blob/master/spec/opreturn-prefix-guideline.md) indicates _little-endian only_, and provides an example for the sake of clarity.

Hope it helps.
