### ISSUE TITLE
Protocol Identifier: Cash Accounts

### ISSUE THREAD

**Issue by monsterbitar** [Lokad/Terab#35]
Requesting the 0x 01010101 identifier for the Cash Accounts protocol.

A display name for the protocol: Cash Accounts
An author (or list of authors): Jonathan Silverblood
A URL pointing to the specification of the protocol: https://gitlab.com/cash-accounts/specification (not yet published)

**Comment by vermorel** [comment]
Hi Jonathan, thanks for your interest! I am currently in the process of migrating this list of protocols to the BCH community repository at https://github.com/bitcoincashorg/bitcoincash.org/pull/173 We will take care of your request once the transition is completed. Sorry for the delay.

**Comment by vermorel** [comment]
Hi Jonathan, the list has been moved at https://github.com/bitcoincashorg/bitcoincash.org/blob/master/etc/protocols.csv. You can forward you request over there.
