### ISSUE TITLE
Reserve 0-1024 ids for trustless/decentralized replacements

### ISSUE THREAD

**Issue by bvk** [Lokad/Terab#8]
I suggest to reserve 0-1024 ids for TCP/IP services with their corresponding trustless/decentralized replacements in future. For example, id 53 could be for trustless/decentralized DNS service of the future.

**Comment by vermorel** [comment]
The guideline has plenty of provisions already to support those cases. While the guideline recommends  4-byte prefixes, it remains possible to introduce 2-byte prefixes that are guaranteed to be non colliding with the 4-byte ones. Thus, we already have "reserved" ids, and a lot more than 1024 :-) . Time will tell how those shorter ids (reserved) should be used.
